### ISSUE TITLE
SonarQube has stopped working

### ISSUE THREAD

**Issue by dannythomas13** [vanderby/SonarQube-AzureAppService#10]
This has been up and running without issue for a couple of months which was great. I recently found that a couple of builds had failed due to SonarQube self updating, no big issue I thought I'll just give it time but it now appears to have stopped working completely and I get 502 (502 - Web server received an invalid response while acting as a gateway or proxy server.), I have no idea how I can fix it as my only access was to the site dashboard, can anyone suggest anything or have faced the same issue over the past week? 
Will I have to face the pain of simply re-deploying a new instance?

**Comment by vanderby** [comment]
SQ recently bumped the Java requirement to 11. You'll have to update the version of Java in the app settings.

-Nate

**Comment by dannythomas13** [comment]
Thanks @vanderby but that didn't get it working for me. I have deployed a new instance and copied over configuration, very shortly after I now see the following: SonarQube is under maintenance
While waiting, you might want to investigate new plugins to extend the current functionality.

If you are an administrator and have no idea why this message is being shown, you should read the upgrade guide.

This same message of upgrade was displayed last time just before it stopped working and has now been running for nearly 24 hours, is that normal or do I need to restart the app service?

**Comment by vanderby** [comment]
Did you follow the upgrade guide at <https://docs.sonarqube.org/latest/setup/upgrading/>? You may need to navigate to <http://yourSonarQubeServerURL/setup> to initiate the database upgrade.

Take a look at the sonar.log and web.log file from the logs folder and see if there are any relevant errors there.

**Comment by dannythomas13** [comment]
Navigating to /setup was all that was needed, thank you so much @vanderby !
