### ISSUE TITLE
SQ comments all lines in sonar.properties when restarted

### ISSUE THREAD

**Issue by lopeg** [vanderby/SonarQube-AzureAppService#18]
Hello
Thank you for great config.
I have very strange case.
i update sonar.properties. (sql connection info), restart SQ (both as web app from azure portal or from SQ UI)
and it just comments my string. not replaces, but comment. every time i restart SQ
Can you please help me in fixing that?

**Comment by vanderby** [comment]
Sounds like a bug in my logic. 

As a work around for now you should be able to set the same properties in the App Settings of the Web App and it will set the matching settings in the sonar.properties file.

**Comment by lopeg** [comment]
and this could help you in fixing bug.
it not only comment, it replace all 'sonar' words by '#sonar.' by regexp
for example
i set line
sonar.jdbc.url=jdbc:sqlserver://my-sonarqube.database.windows.net,1433;databaseName=sonar;encrypt=true;

after restart it is transformed to 
#sonar.jdbc.url=jdbc:sqlserver://my-#sonar.ube.database.windows.net,1433;databaseName=#sonar.encrypt=true;

take a look at #sonar. in the midle of line

**Comment by vanderby** [comment]
Should be fixed by #19 
Remember settings should be set in the app service config and not directly in sonar.properties else they will be overridden.
Reopen if it is not.
