### ISSUE TITLE
Azure Sql database changes not working with Azure app service!! How to change Admin Password??

### ISSUE THREAD

**Issue by connectgirish3** [vanderby/SonarQube-AzureAppService#27]
Hi Vanderby,
I have updated the sql database config changes in app settings.  I restarted the azure app. Still it is showing unauthorized. I am using default sa user credentials.  Could you please advice on the same.

2019.11.20 00:01:52 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory D:\home\site\wwwroot\sonarqube-8.0\temp

WrapperSimpleApp: Encountered an error running main: java.nio.file.FileSystemException: D:\home\site\wwwroot\sonarqube-8.0\temp\ce-exploded-plugins\csharp\sonar-csharp-plugin-7.17.0.9346.jar: The process cannot access the file because it is being used by another process.

java.nio.file.FileSystemException: D:\home\site\wwwroot\sonarqube-8.0\temp\ce-exploded-plugins\csharp\sonar-csharp-plugin-7.17.0.9346.jar: The process cannot access the file because it is being used by another process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.base/java.nio.file.Files.delete(Unknown Source)
	at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:192)
	at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:186)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at org.sonar.process.FileUtils2.deleteDirectoryImpl(FileUtils2.java:148)
	at org.sonar.process.FileUtils2.deleteDirectory(FileUtils2.java:121)
	at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:117)
	at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:101)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at org.sonar.application.AppFileSystem.createOrCleanTempDirectory(AppFileSystem.java:96)
	at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:62)
	at org.sonar.application.App.start(App.java:62)
	at org.sonar.application.App.main(App.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
	at java.base/java.lang.Thread.run(Unknown Source)
<-- Wrapper Stopped
Unable to set the process priority:  Access is denied. (0x5)
Attempt to set the console title failed: The handle is invalid. (0x6)
--> Wrapper Started as Console
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2019.11.20 00:03:12 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory D:\home\site\wwwroot\sonarqube-8.0\temp
2019.11.20 00:03:13 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.11.20 00:03:14 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [D:\home\site\wwwroot\sonarqube-8.0\elasticsearch]: D:\Program Files\Java\zulu11.29.3-jre11.0.2-win_x64\bin\java -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.io.tmpdir=D:\home\site\wwwroot\sonarqube-8.0\temp -XX:ErrorFile=../logs/es_hs_err_pid%p.log -Des.enforce.bootstrap.checks=true -Xmx512m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Delasticsearch -Des.path.home=D:\home\site\wwwroot\sonarqube-8.0\elasticsearch -Des.path.conf=D:\home\site\wwwroot\sonarqube-8.0\temp\conf\es -cp lib/* org.elasticsearch.bootstrap.Elasticsearch
2019.11.20 00:03:14 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.11.20 00:03:15 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.11.20 00:03:15 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2019.11.20 00:04:10 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2019.11.20 00:04:10 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [D:\home\site\wwwroot\sonarqube-8.0]: D:\Program Files\Java\zulu11.29.3-jre11.0.2-win_x64\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=D:\home\site\wwwroot\sonarqube-8.0\temp --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/common/*;D:\home\site\wwwroot\sonarqube-8.0\lib\jdbc\mssql\mssql-jdbc-7.2.2.jre11.jar org.sonar.server.app.WebServer D:\home\site\wwwroot\sonarqube-8.0\temp\sq-process6862961921063235828properties
2019.11.20 00:15:30 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2019.11.20 00:15:30 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='ce', ipcIndex=3, logFilenamePrefix=ce]] from [D:\home\site\wwwroot\sonarqube-8.0]: D:\Program Files\Java\zulu11.29.3-jre11.0.2-win_x64\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=D:\home\site\wwwroot\sonarqube-8.0\temp --add-opens=java.base/java.util=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/common/*;D:\home\site\wwwroot\sonarqube-8.0\lib\jdbc\mssql\mssql-jdbc-7.2.2.jre11.jar org.sonar.ce.app.CeServer D:\home\site\wwwroot\sonarqube-8.0\temp\sq-process5618927092452894067properties
2019.11.20 00:15:49 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
2019.11.20 00:15:49 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up

**Comment by vanderby** [comment]
@connectgirish3 
The default SQ login creds don't change when Azure SQL is the backend. Username: Admin Password: Admin

From the log you posted it appears SQ started up fine.
```
2019.11.20 00:04:10 INFO app[][o.s.a.SchedulerImpl] Process[es] is up
...
2019.11.20 00:15:30 INFO app[][o.s.a.SchedulerImpl] Process[web] is up
...
2019.11.20 00:15:49 INFO app[][o.s.a.SchedulerImpl] Process[ce] is up
2019.11.20 00:15:49 INFO app[][o.s.a.SchedulerImpl] SonarQube is up
```

You can probably ignore the FileSystemException for the csharp plugin as the app seemed to restart based on the log. I suspect 2 instances were trying to start up at the same time. In that case one will fail and one will succeed. I don't see any database errors in the log you posted so I suspect the app can properly communicate with SQL Azure.

**Comment by vanderby** [comment]
Closing to lack of response.
