### ISSUE TITLE
App service poor performance

### ISSUE THREAD

**Issue by nk111** [vanderby/SonarQube-AzureAppService#29]
We compared the performance of this solution against a vm approach. It took the sonarqube vm 3 minutes to analyze the scan results while the app service needed 1 hour and 3 minutes! Our app service is on a S1 plan and we analyzed a ~500k lines of coude project with several thousand warnings in the result.

Are there any settings we could make for the app service to increase performance? What would you say is the minimum sku to get a _usable_ solution for medium to large projects?

**Comment by vanderby** [comment]
I have not done a analysis for scans. I only looked at startup times and the startup time was reduced roughly proportionally to the more cores it had to work with. It was also a bit faster when moving from Basic to Standard to Premium. I can't find the raw numbers so I must have deleted it.

What VM SKU were you using? I'm going to presume the scan is CPU bound. S1 only has 1 core, S2 has 2 and S3 has 4. The Premium SKUs run on the Dv2 series VMs and come with SSD and faster processors.

Info on web app SKUs can be found here. https://azure.microsoft.com/en-us/pricing/details/app-service/windows/

I'd be curious to hear back what you find. I'd love to add it to the readme for everyone's reference. It shouldn't be too difficult to do a sample scan on each SKU.

**Comment by vanderby** [comment]
Closing due to lack of response.
