### ISSUE TITLE
Developer Edition

### ISSUE THREAD

**Issue by brkakkaya** [vanderby/SonarQube-AzureAppService#30]
Hi @vanderby ,

I have tried to deploy the Sonarqube developer edition to azure web service, but I couldn't achieve that. I have selected the sonarqube version as the developer edition on the "deploy azure" menu, but my sonarqube service still community edition.

Could you please help me with this issue? Is there a point I missed?

Thanks,
Burak

**Comment by vanderby** [comment]
@brkakkaya Thanks for raising this issue. It appears the app settings are no longer being set as specified in the ARM template and we default to the community edition.

I'll investigate further and report back later this week.

**Comment by vanderby** [comment]
I was able to deploy a developer edition yesterday. I think this was an issue with Azure that has been resolved.
