### ISSUE TITLE
Deploy to azure button not working?

### ISSUE THREAD

**Issue by nk111** [vanderby/SonarQube-AzureAppService#32]
ATM the deploy to azure button doesn't let me create the app service in an existing resource group.

![image](https://user-images.githubusercontent.com/155322/76623021-ec924300-6532-11ea-8c60-9480edfdb81c.png)

I do have contributor rights on that resource group and i am able to create resources in it via the azure portal.

Any hints?

**Comment by vanderby** [comment]
@nk111 
You would have to look in Azure AD on the specific permissions that client/object id has given the scope in the error message. Its possible its a different permission or object id then what you logged into the portal with.

You could also deploy the project using one of the links in the [Deploy Using Azure Portal](https://github.com/vanderby/SonarQube-AzureAppService#deploy-using-azure-portal) section. That will redirect you to the Azure portal template deployment wizard and pre-load a bunch of defaults.

**Comment by nk111** [comment]
@vanderby Thanks! I'll try to log off from portal before the next try. 

the "Deploy to azure public cloud" link gives me this btw:

![image](https://user-images.githubusercontent.com/155322/76646691-b0bfa380-655b-11ea-9ad1-0d8503b69924.png)

**Comment by vanderby** [comment]
That's frustrating since the page is public and the URL is correct. I've repo'd the issue so I'll dig into it. I'm not sure when this broke.

In the Azure template deployment you can always select "Build your own template in the editor" and paste the azuredeploy.json file.

**Comment by vanderby** [comment]
Issue should be fixed with latest commit. There was a trailing comma in the App Service SKU list that the custom template deployment didn't like.
