### ISSUE TITLE
Sonarqube are using Revisions in their version number, and it breaks the downloader

### ISSUE THREAD

**Issue by Rincey** [vanderby/SonarQube-AzureAppService#33]
The downloader regex '\d+.\d+.?(\d+)?.zip' is expecting a version number in the style #.#.# but for the last two releases they have used a Revision number (#.#.#.# eg 8.2.0.32929).

I tweaked the regex for my install to '\d+(.\d+)*.zip' which seems to work for now, but I don't know if it robust to survive further combinations. You might want to double check my regex logic :)

**Comment by vanderby** [comment]
Thanks for pointing this out I'll take a look today.
