### ISSUE TITLE
App service unable to launch with Azure SQL

### ISSUE THREAD

**Issue by youdhbir** [vanderby/SonarQube-AzureAppService#42]
Hello Vanderby,

This is a simple integration with Azure SQL but unfortunately not working for me. JDBC settings are updated per instructions and can see reflecting in sonar.properties file as well.

It always return generic errors either
"502 - Web server received an invalid response while acting as a gateway or proxy server." or 
"The specified CGI application encountered an error and the server terminated the process."

No firewall configured for Azure SQL server and verified as I'm able to connect to Azure SQL db using SSMS.

Enabled app insights and log analytics but no hint. I can see that every time I restart app service, all steps in powershell run and logged properly.

Could you please help. Thanks.

**Comment by vanderby** [comment]
Only two things comes to mind:
1. Verify the connection string is correct.
1. Verify the firewall settings on Azure SQL

**Comment by youdhbir** [comment]
Thanks for quick response!

Both verified but seems correct to me.

Connection string: jdbc:sqlserver://<dbserver>:1433;database=<database>;encrypt=true;
DB Server firewall: No firewall. (Screenshot attached)

<img width="595" alt="SQLServer-Firewall" src="https://user-images.githubusercontent.com/9878892/81410877-18aaf880-915f-11ea-91d2-7a615260e176.png">

This is a very basic problem but very important for running SonarQube as Azure App Service. I've tried to deploy template multiple times, just to ensure SonarQube service is running. Already had a setup on VM and now moving to App service due to numerous benefits.

**Comment by vanderby** [comment]
I finally got some time to circle back to this.

I have this working as expected. You should get more information from the logs\web.log. Easiest way to read the file is to use the "App Service Editor (Preview)" in the Development Tools section.

Did you create the database as SQL_Latin1_General_CP1_CS_AS? The default is SQL_Latin1_General_CP1_CI_AS which SQ does not like.

My firewall settings are the same as yours. And my application settings are what is specified in the project readme.
![image](https://user-images.githubusercontent.com/28767221/81488839-16669e00-9234-11ea-8ba1-5feb5ef5eb89.png)

**Comment by vanderby** [comment]
Closing this out due to inactivity.

**Comment by youdhbir** [comment]
Database collation was the issue. Many thanks for the support @vanderby !

**Comment by danielrwoodward** [comment]
@vanderby we are having this exact same issue, and are at a loss, is there any other guidance? Are "-" an invalid character in the url perhaps?

**Comment by danielrwoodward** [comment]
@vanderby the issue was the url, we removed everything except the following - `jdbc:sqlserver://XXXXXXX.database.windows.net:1433;database=XXXX;`

It needs no other parameters, despite what many people claim lol
