### ISSUE TITLE
Deploying with Private Repo

### ISSUE THREAD

**Issue by ArpanBalpande** [vanderby/SonarQube-AzureAppService#43]
Hi
I'm trying to deploy SonarQube into Azure App service using the same scripts inside this repository. But for my use case, I want to deploy the code (scripts) directly from my Private Azure Repo instead of going through the Public GitHub repo as a value to the "repoUrl" parameters. Can you please help me with the same?

**Comment by vanderby** [comment]
Looking at the [sourcecontrols](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2019-08-01/sites/sourcecontrols) API I don't see anything that would indicate it works with private repos.

If I were you. I would make multiple pipelines. First I remove the [sourcecontrols section](https://github.com/vanderby/SonarQube-AzureAppService/blob/f0ce386fe0bc9acd518255b00ecbadd4b7d7ea01/azuredeploy.json#L119) of the ARM template. This allows you to deploy just the Azure resources. Then I would setup another pipeline to [deploy the app code](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml).

The final caveat is executing [Deploy-SonarQubeAppService.ps1](https://github.com/vanderby/SonarQube-AzureAppService/blob/master/Deploy-SonarQubeAzureAppService.ps1). For the Deploy To Azure in this repo this happens from the [.deployment](https://github.com/vanderby/SonarQube-AzureAppService/blob/master/.deployment) file. This file may not execute depending on how you deploy files to the app service. If the file doesn't execute automatically a possible solution would be to execute this file as a part of your app code deployment pipeline before its pushed to the web app. Or if you don't deploy very often you could run it manually.

Good luck with your endeavors.

**Comment by vanderby** [comment]
Close this out due to inactivity.

**Comment by ArpanBalpande** [comment]
Apologies for the late reply. But this was super helpful and we were able to deploy SonarQube. Thanks a lot @vanderby  😄👍
