### ISSUE TITLE
Deploying with existing App Service Plan

### ISSUE THREAD

**Issue by nmehlei** [vanderby/SonarQube-AzureAppService#44]
Is this a supported scenario? I already have several App Services running in an existing App Service Plan, thus it would not make much sense to create a new one just for this one application. Did I miss something on how to re-use an existing App Service Plan?

**Comment by vanderby** [comment]
Yep. Use one of the links under [Deploy Using Azure Portal](https://github.com/vanderby/SonarQube-AzureAppService#deploy-using-azure-portal).

This is a standard ARM template deployment so it will create the resource if it doesn't exist or use an existing one if it does exist.

**Comment by nmehlei** [comment]
Well, crap, sorry, must've completely missed that.

For anyone trying the same, as the ARM template does not allow for setting a different resource group for the App Service Plan, one has to create the App Service inside the same RG as the App Service Plan and afterward move it to the targeted RG, otherwise, it will create an additional App Service Plan.

**Comment by vanderby** [comment]
You could also edit the template in the Azure Portal before deployment to change that relationship if you are familiar with ARM templates.
