### ISSUE TITLE
How to increase max request length ? 

### ISSUE THREAD

**Issue by LvffY** [vanderby/SonarQube-AzureAppService#53]
Hi,

We're using your (great) code to deploy our Sonarqube in Azure Webapp. 

It works like a charm, except for one feature. When we analysed a project, we'd like to go to the window "measures" but when we get here, we only get some `The request cannot be processed. Try again later.`

<img width="960" alt="sonar_issue" src="https://user-images.githubusercontent.com/37327656/133738739-80df3062-b7a3-4fff-b98c-2eb9816ead9f.png">

Actually, [after some digging](https://community.sonarsource.com/t/the-request-cannot-be-processed-try-again-later/8295), it turns out this seems to be some kind of badly configuration set up. 

But because I'm (really) not an expert in Azure web app, I don't know where to "increase this request size". 

Could you help me on this ? *May be you already have this kind of issue and I'm totally misunderstanding the problem*

Best regards, 

LvffY

**Comment by vanderby** [comment]
I am glad you find it useful @LvffY!

I have not ran into query length issues myself, but doing some internet research it appears a web.config in the wwwroot folder should help you out.
* http://andredublin.github.io/.net/2014/06/26/large-query-string-values-and-azure.html
* https://stackoverflow.com/questions/16026142/windows-azure-websites-maxquerystringlength
* https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by LvffY** [comment]
Hello @vanderby 

That perfectly solved my issue :)

For anyone who's falling in here, I made the changes explained in [first link](http://andredublin.github.io/.net/2014/06/26/large-query-string-values-and-azure.html) pointed by @vanderby. 

Concretely, I changed my file `C:\home\site\wwwroot\web.config` (because of my windows setup, probably `/home/site/wwwroot/web.config` in Linux setup) and add the following lines in the **security.webServer** section :  

```xml
<security>
  <requestFiltering>
     <!-- 5000 is an arbitrary choice based on the request that failed for me -->
    <requestLimits maxQueryString="5000" />
  </requestFiltering>
</security>
``` 

@vanderby May be you could pin this issue to avoid you to answer another issue on this point ? 

Anyway, thanks a lot for your help !

Best regards, 

LvffY
