### ISSUE TITLE
sonar.properties and wrapper.conf grows large with repetition

### ISSUE THREAD

**Issue by zemien** [vanderby/SonarQube-AzureAppService#54]
I have some JDBC settings in the App Service configuration, which gets injected into sonar.properties correctly..... except it seems to replicate the whole file contents a few hundred times. A fresh install is 21kb, but after starting up it grows to 42201kb! It's the same 400 lines (with the right replacements) copied repeatedly.

Same thing with the wrapper.conf - it grows to 14114kb

I was under the impression the HttpPlatformHandler.ps1 file replaces the content rather than appends it to the end. I did not change the script at all from the latest master copy.

The file seems to be capped at that size. It doesn't double every time I restart the Web App either. Weird!

Anyone else having this issue?

**Comment by jstevense-vbe** [comment]
Been having the same issue here... after an update I uncomment that part in HttpPlatformHandler.ps1 
But a permanent fix would be nice

**Comment by vanderby** [comment]
Should be fixed in #72
