### ISSUE TITLE
How to upgrade this solution to solve the Log4J security issue?

### ISSUE THREAD

**Issue by gpaulissen** [vanderby/SonarQube-AzureAppService#58]
Since a few months there is a Log4J bug which concerns the current SonarQube production instance. I want to upgrade the Azure app service and the only thing I found was a comment about a deployment slot on [SonarQube Hosted On Azure App Service](https://devblogs.microsoft.com/premier-developer/sonarqube-hosted-on-azure-app-service/). However since that information does not help very much, I created a deployment slot using the External Git repo variant. The deployment succeeded but the SonarQube instnce does not come up (The specified CGI application encountered an error and the server terminated the process). SonarQube logs do not really help neither. So I can not upgrade this way. Did I do something wrong or is there another way?

By the way, the SonarQube production version is 9.2.1 (build 49989). The upgrade version is 9.2.4, build 50792.

**Comment by naveenatwork** [comment]
I found this upgrade sonarqube steps useful:
https://github.com/vanderby/SonarQube-AzureAppService/issues/52
I think it is best to add it to the readme page.

**Comment by itsBrock** [comment]
@gpaulissen what I ran into running in a slot is elasticsearch bindings were throwing errors about being in use, so in the slot  I had to change ES ports.  

I got 9.2.4 running in prod but my analysis is throwing an error .  Idk if it's related to this specific version or if you ran into it using 9.2.1
ERROR: Error during SonarScanner execution
java.lang.UnsupportedClassVersionError: org/sonar/batch/bootstrapper/EnvironmentInformation has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by vanderby** [comment]
@itsBrock, SQ v9.2 moved to Java 11. Update your app service's version of Java from 10 to 11.
