### ISSUE TITLE
Sonarqube 9.2.4 upgrade

### ISSUE THREAD

**Issue by itsBrock** [vanderby/SonarQube-AzureAppService#59]
So we upgraded to Sonarqube version 9.2.4 and everything appeared to work until we run our first build and it errored out on the analysis with the error

ERROR: Error during SonarScanner execution
java.lang.UnsupportedClassVersionError: org/sonar/batch/bootstrapper/EnvironmentInformation has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Anyone successfully get version 9.2.4 running in an app service?  My web app is configured for Java 11 and minor is 11 with auto upgrade.  Any thoughts?

**Comment by sylvain-combe-sonarsource** [comment]
Hi @itsBrock 
as per [SonarQube Release Upgrade notes](https://docs.sonarqube.org/latest/setup/upgrade-notes/#header-3), Java 11 is  requested on the scanner/pipeline side as well when used with SonarQube 9.x
Feel free to raise any issue with the [SonarSource community](https://community.sonarsource.com/).
