### ISSUE TITLE
Ghost duplicated

### ISSUE THREAD

**Issue by savethekiddes** [vanderby/SonarQube-AzureAppService#61]
I’ve tried to deploy sonarqube, and it follows the following error
    "status": "Failed", 
   "error": {        "code": "Conflict",        "message": "Website with given name SonarQubeAppService already exists.",        "details": [            {                "message": "Website with given name SonarQubeAppService already exists."            },            {                "code": "Conflict"            },            {}        ]    }}
   But when I go to the webapp list “SonarQubeAppService” doesn’t show up

**Comment by vanderby** [comment]
The website name has to be globally unique across public Azure. It probably exists in another person subscription.
https://sonarqube.azurewebsites.net
