### ISSUE TITLE
Sensitive environment variables should not be logged by HttpPlatformHandlerStartup.ps1

### ISSUE THREAD

**Issue by EgorEmeliyanov** [vanderby/SonarQube-AzureAppService#66]
I would comment out line 69 of [HttpPlatformHandlerStartup.ps1](https://github.com/vanderby/SonarQube-AzureAppService/blob/master/wwwroot/HttpPlatformHandlerStartup.ps1). I understand that these logs are not downloadable externally, but nonetheless having plaintext passwords in a log file is not a good practice.

**Comment by vanderby** [comment]
Submit a PR.

**Comment by vanderby** [comment]
!67
