### ISSUE TITLE
Could not find wrapper.conf in Sonarqube 9.6 version 

### ISSUE THREAD

**Issue by sravansagi** [vanderby/SonarQube-AzureAppService#69]
Hello, When we are trying to deploy with Sonarqube version of 9.6 we are encountering below error. Seems like sonarqube has removed `wrapper.conf` file. 

```
9:30:55 AM Updating sonar.web.port to 16316
9:30:55 AM Saving updated sonar.properties contents
9:30:55 AM Searching for wrapper.conf file
9:30:56 AM Could not find wrapper.conf
```
Here is the thread around the same -> https://community.sonarsource.com/t/wrapper-conf-missing-from-9-6-zip-files/70161

May be required HttpPlatformHandlerStartup.ps1 should be updated to be using the new way of launching sonarqube.

**Comment by vanderby** [comment]
Fixed with #70
