### ISSUE TITLE
How to change the DB?

### ISSUE THREAD

**Issue by mustafababil** [vanderby/SonarQube-AzureAppService#7]
This deployment comes with embedded H2 database.
How can I change it to PostgreSQL?

I added the keys with appropriate values to Application Settings, but it still works on H2.
```
SONARQUBE_JDBC_USERNAME
SONARQUBE_JDBC_PASSWORD
SONARQUBE_JDBC_URL
```

**Comment by vanderby** [comment]
You cannot set properties through the app settings. You need to change the sonarqube-X.X\conf\sonar.properties file with these settings then restart the web app. Easiest way to do that is change the file using the App Service Editor blade or the appService.scm.azurewebsites.net site.

**Comment by mustafababil** [comment]
Preview version of App Service Editor just works. Thanks for the info. I was migrated database to Postgre.

**Comment by vanderby** [comment]
@mustafababil I have added the ability to set SQ settings from the Azure application settings.

Anything prefixed with "sonar." will set the setting in sonar.properties.
Anything prefixed with "wrapper." will set the setting in wrapper.conf.
