### ISSUE TITLE
My SonarQube Server is Saying UnderMaintainance

### ISSUE THREAD

**Issue by seshagirirao-nadakuditi** [vanderby/SonarQube-AzureAppService#73]
I have used the Direct Approach and Added the External Git url to my Azure App Service. It is working fine till last month but suddenly stopped working. So, i did sync and now its asking for upgrade. Can you please tell me what needs to be done for this.
![image](https://user-images.githubusercontent.com/113963679/200845156-1266b2f1-357c-4111-9300-06d4869778a5.png)

Can you please suggest what needs to be done.

**Comment by LauraSilvaAyala** [comment]
Hi! you just have to use the same URL for application but at the end use /setup

After that you have to update and will be ok

**Comment by retikagupta** [comment]
Your database is using a different version of SonarQube than the one you are trying to install.

**Comment by seshagirirao-nadakuditi** [comment]
> Hi! you just have to use the same URL for application but at the end use /setup
> 
> After that you have to update and will be ok

thank you this helped. After /setup this issue was resolved.
